# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 88bef0770b38a519690ae42aef65da41711f43f144b9461f869907fe3aef6f641bf5cfda99a85afac4d73b552ab79651ee5ff5068aca4a08fbd2e2a12152b4eb

test:
  secret_key_base: 355c06c46cd55ac1c91c3915aeefae0293e5fca8c9dae9021afe7a64f73e153b47f394b745a744291886a8d9a7dcb5deadbe339d3e4bc1e66d4605bede795a6c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
